SET TIME ZONE 'UTC';

DROP TABLE IF EXISTS
    hw2_customer_features_online,
    hw2_training_events,
    hw2_customer_features_offline,
    hw2_order_items,
    hw2_orders,
    hw2_products,
    hw2_categories,
    hw2_customers
CASCADE;

-- =========================================================
-- Бізнесові сутності (нормалізовані, 3НФ)
-- =========================================================

CREATE TABLE hw2_customers (
    customer_id      BIGINT       PRIMARY KEY,
    email            VARCHAR(255) NOT NULL UNIQUE,
    signup_date      DATE         NOT NULL,
    country          VARCHAR(2)   NOT NULL
        CHECK (country ~ '^[A-Z]{2}$'),
    marketing_opt_in BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE hw2_categories (
    category_id INTEGER      PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE hw2_products (
    product_id  BIGINT        PRIMARY KEY,
    category_id INTEGER       NOT NULL
        REFERENCES hw2_categories(category_id),
    name        TEXT          NOT NULL,
    list_price  NUMERIC(10, 2) NOT NULL
        CHECK (list_price >= 0),
    is_active   BOOLEAN       NOT NULL DEFAULT TRUE
);

CREATE TABLE hw2_orders (
    order_id    BIGINT      PRIMARY KEY,
    customer_id BIGINT      NOT NULL
        REFERENCES hw2_customers(customer_id),
    order_ts    TIMESTAMPTZ NOT NULL,
    status      VARCHAR(20) NOT NULL
        CHECK (status IN ('paid', 'shipped', 'delivered', 'cancelled', 'returned'))
);

-- Bridge-таблиця для природного зв'язку N:M orders <-> products
CREATE TABLE hw2_order_items (
    order_id   BIGINT         NOT NULL
        REFERENCES hw2_orders(order_id) ON DELETE CASCADE,
    product_id BIGINT         NOT NULL
        REFERENCES hw2_products(product_id),
    quantity   INTEGER        NOT NULL
        CHECK (quantity > 0),
    unit_price NUMERIC(10, 2) NOT NULL
        CHECK (unit_price >= 0),

    PRIMARY KEY (order_id, product_id)
);

-- Основний access pattern для розрахунку ознак:
-- замовлення конкретного клієнта за часовим вікном
CREATE INDEX hw2_idx_orders_customer_ts
    ON hw2_orders (customer_id, order_ts);

-- =========================================================
-- Offline-рівень feature store: історія версій ознак
-- Кожна версія чинна на інтервалі [valid_from, valid_to)
-- =========================================================

CREATE TABLE hw2_customer_features_offline (
    customer_id             BIGINT         NOT NULL
        REFERENCES hw2_customers(customer_id),
    valid_from              TIMESTAMPTZ    NOT NULL,
    valid_to                TIMESTAMPTZ,
    orders_30d              INTEGER        NOT NULL
        CHECK (orders_30d >= 0),
    spend_30d               NUMERIC(12, 2) NOT NULL
        CHECK (spend_30d >= 0),
    days_since_last_order   INTEGER
        CHECK (days_since_last_order IS NULL OR days_since_last_order >= 0),
    distinct_categories_90d INTEGER        NOT NULL
        CHECK (distinct_categories_90d >= 0),

    PRIMARY KEY (customer_id, valid_from),

    CHECK (valid_to IS NULL OR valid_to > valid_from)
);

-- AS-OF lookup: остання версія з valid_from <= ts для клієнта
CREATE INDEX hw2_idx_customer_features_asof
    ON hw2_customer_features_offline (customer_id, valid_from DESC);

-- Для кожного клієнта може існувати не більше однієї поточної версії
CREATE UNIQUE INDEX hw2_uq_customer_features_current
    ON hw2_customer_features_offline (customer_id)
    WHERE valid_to IS NULL;

-- =========================================================
-- Training events: момент прогнозу + цільова змінна
-- =========================================================

CREATE TABLE hw2_training_events (
    event_id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id       BIGINT      NOT NULL
        REFERENCES hw2_customers(customer_id),
    prediction_ts     TIMESTAMPTZ NOT NULL,
    label_horizon_end TIMESTAMPTZ NOT NULL,
    churn_in_horizon  BOOLEAN     NOT NULL,

    UNIQUE (customer_id, prediction_ts),
    CHECK (label_horizon_end > prediction_ts)
);

-- =========================================================
-- Online-рівень feature store: один денормалізований рядок
-- на клієнта (лише поточні значення) для швидкого lookup
-- =========================================================

CREATE TABLE hw2_customer_features_online (
    customer_id             BIGINT         PRIMARY KEY
        REFERENCES hw2_customers(customer_id),
    country                 VARCHAR(2)     NOT NULL,
    signup_date             DATE           NOT NULL,
    orders_30d              INTEGER        NOT NULL
        CHECK (orders_30d >= 0),
    spend_30d               NUMERIC(12, 2) NOT NULL
        CHECK (spend_30d >= 0),
    days_since_last_order   INTEGER
        CHECK (days_since_last_order IS NULL OR days_since_last_order >= 0),
    distinct_categories_90d INTEGER        NOT NULL
        CHECK (distinct_categories_90d >= 0),
    feature_ts              TIMESTAMPTZ    NOT NULL,
    updated_at              TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
